# Generated by Django 4.1.7 on 2023-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("started", "started"), ("completed", "completed")],
                        max_length=500,
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "app_name",
                    models.CharField(
                        choices=[
                            ("myapp", "myapp"),
                            ("test_case_run", "test_case_run"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("test_case", models.TextField(unique=True)),
            ],
        ),
    ]
